post_install() {
    # Bash completion — always install
    /opt/bin/stubber completion bash > /etc/bash_completion.d/stubber

    # Zsh completion — only if zsh is present
    if command -v zsh > /dev/null 2>&1; then
        mkdir -p /usr/share/zsh/site-functions
       /opt/bin/stubber completion zsh > /usr/share/zsh/site-functions/_stubber
    fi
}

post_upgrade() {
    post_install
}

post_remove() {
    rm -f /etc/bash_completion.d/stubber
    rm -f /usr/share/zsh/site-functions/_stubber
}